# Generated by Django 5.2.1 on 2025-06-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Используется для {% draw_menu "name" %}', max_length=30, unique=True, verbose_name='Имя')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='заголовок пункта меню')),
                ('url', models.CharField(blank=True, help_text='например, /contacts/', max_length=50, verbose_name='явный URL')),
                ('named_url', models.CharField(blank=True, help_text='например, app:view_name', max_length=50, verbose_name='именованный URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок сортировки')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu', verbose_name='меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
